version: '2'
services: 
  commander:
    image: isaacp/itey:latest
    ports:
      - "80:80"
    privileged: true
    environment:
#      - SERIAL_PORT=/dev/ttyS0
#      - SERIAL_PORT=/dev/serial1
      - SERIAL_PORT=/dev/ttyAMA0
    devices:
      - /dev/ttyAMA0:/dev/ttyS0
      - /dev/ttyAMA0:/dev/ttyAMA0
      - /dev/serial0:/dev/serial0
      - /dev/serial1:/dev/serial1
    cap_add:
      - SYS_RAWIO
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
      bump: '1'
